nines_media:
    root: 'data'
    thumb_width: 450
    thumb_height: 350
    routing:
        - { class: App\Entity\Person, route: person_show }
        - { class: App\Entity\Book, route: person_show }
        - { class: App\Entity\Compilation, route: book_show }
        - { class: App\Entity\Periodical, route: periodical_show }
