nines_util:
    trim_length: 50
    routing:
        - { class: App\Entity\Person, route: person_show }
        - { class: App\Entity\Book, route: person_show }
        - { class: App\Entity\Compilation, route: book_show }
        - { class: App\Entity\Periodical, route: periodical_show }
